//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace MetaTraderConversionLib.Xml.DIFI {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd", IsNullable=false)]
    public partial class Envelope {
        
        private Header headerField;
        
        private AttachmentListExternalAttachment[] attachmentListField;
        
        private Signatures signaturesField;
        
        private EnvelopeBody bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
        public Header Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ExternalAttachment", IsNullable=false)]
        public AttachmentListExternalAttachment[] AttachmentList {
            get {
                return this.attachmentListField;
            }
            set {
                this.attachmentListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
        public Signatures Signatures {
            get {
                return this.signaturesField;
            }
            set {
                this.signaturesField = value;
            }
        }
        
        /// <remarks/>
        public EnvelopeBody body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd", IsNullable=false)]
    public partial class Header {
        
        private taxPayerType taxpayerField;
        
        private string responseToField;
        
        private workflowType workflowField;
        
        private custodianType custodianInfoField;
        
        private string domainField;
        
        /// <remarks/>
        public taxPayerType taxpayer {
            get {
                return this.taxpayerField;
            }
            set {
                this.taxpayerField = value;
            }
        }
        
        /// <remarks/>
        public string responseTo {
            get {
                return this.responseToField;
            }
            set {
                this.responseToField = value;
            }
        }
        
        /// <remarks/>
        public workflowType Workflow {
            get {
                return this.workflowField;
            }
            set {
                this.workflowField = value;
            }
        }
        
        /// <remarks/>
        public custodianType CustodianInfo {
            get {
                return this.custodianInfoField;
            }
            set {
                this.custodianInfoField = value;
            }
        }
        
        /// <remarks/>
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class taxPayerType {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private taxpayerTypeType taxpayerTypeField;
        
        private bool taxpayerTypeFieldSpecified;
        
        private string nameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string postNumberField;
        
        private string postNameField;
        
        private string municipalityNameField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string maticnaStevilkaField;
        
        private bool invalidskoPodjetjeField;
        
        private bool invalidskoPodjetjeFieldSpecified;
        
        private bool residentField;
        
        private bool residentFieldSpecified;
        
        private string activityCodeField;
        
        private string activityNameField;
        
        private string countryIDField;
        
        private string countryNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taxNumber", typeof(string), DataType="positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("vatNumber", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public taxpayerTypeType taxpayerType {
            get {
                return this.taxpayerTypeField;
            }
            set {
                this.taxpayerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxpayerTypeSpecified {
            get {
                return this.taxpayerTypeFieldSpecified;
            }
            set {
                this.taxpayerTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string postNumber {
            get {
                return this.postNumberField;
            }
            set {
                this.postNumberField = value;
            }
        }
        
        /// <remarks/>
        public string postName {
            get {
                return this.postNameField;
            }
            set {
                this.postNameField = value;
            }
        }
        
        /// <remarks/>
        public string municipalityName {
            get {
                return this.municipalityNameField;
            }
            set {
                this.municipalityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string maticnaStevilka {
            get {
                return this.maticnaStevilkaField;
            }
            set {
                this.maticnaStevilkaField = value;
            }
        }
        
        /// <remarks/>
        public bool invalidskoPodjetje {
            get {
                return this.invalidskoPodjetjeField;
            }
            set {
                this.invalidskoPodjetjeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invalidskoPodjetjeSpecified {
            get {
                return this.invalidskoPodjetjeFieldSpecified;
            }
            set {
                this.invalidskoPodjetjeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool resident {
            get {
                return this.residentField;
            }
            set {
                this.residentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool residentSpecified {
            get {
                return this.residentFieldSpecified;
            }
            set {
                this.residentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string activityCode {
            get {
                return this.activityCodeField;
            }
            set {
                this.activityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string activityName {
            get {
                return this.activityNameField;
            }
            set {
                this.activityNameField = value;
            }
        }
        
        /// <remarks/>
        public string countryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string countryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        taxNumber,
        
        /// <remarks/>
        vatNumber,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public enum taxpayerTypeType {
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        PO,
        
        /// <remarks/>
        SP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class presentationType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class receiptType {
        
        private System.DateTime timestampField;
        
        private string documentNumberField;
        
        private string nameField;
        
        private string metaText1Field;
        
        private System.DateTime metaDate1Field;
        
        private bool metaDate1FieldSpecified;
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string documentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string metaText1 {
            get {
                return this.metaText1Field;
            }
            set {
                this.metaText1Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime metaDate1 {
            get {
                return this.metaDate1Field;
            }
            set {
                this.metaDate1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metaDate1Specified {
            get {
                return this.metaDate1FieldSpecified;
            }
            set {
                this.metaDate1FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class serverSignerType {
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string nameField;
        
        private string idField;
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class signerType {
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class custodianType {
        
        private string nameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string custodianNotesField;
        
        private System.DateTime custodianSubmitDateField;
        
        private bool custodianSubmitDateFieldSpecified;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string CustodianNotes {
            get {
                return this.custodianNotesField;
            }
            set {
                this.custodianNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime CustodianSubmitDate {
            get {
                return this.custodianSubmitDateField;
            }
            set {
                this.custodianSubmitDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustodianSubmitDateSpecified {
            get {
                return this.custodianSubmitDateFieldSpecified;
            }
            set {
                this.custodianSubmitDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class workflowType {
        
        private string documentWorkflowIDField;
        
        private string documentWorkflowNameField;
        
        /// <remarks/>
        public string DocumentWorkflowID {
            get {
                return this.documentWorkflowIDField;
            }
            set {
                this.documentWorkflowIDField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentWorkflowName {
            get {
                return this.documentWorkflowNameField;
            }
            set {
                this.documentWorkflowNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class AttachmentListExternalAttachment {
        
        private int attachmentIdField;
        
        private bool attachmentIdFieldSpecified;
        
        private string typeField;
        
        private string filenameField;
        
        private string mimetypeField;
        
        private AttachmentListExternalAttachmentHash hashField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int attachmentId {
            get {
                return this.attachmentIdField;
            }
            set {
                this.attachmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentIdSpecified {
            get {
                return this.attachmentIdFieldSpecified;
            }
            set {
                this.attachmentIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        public string mimetype {
            get {
                return this.mimetypeField;
            }
            set {
                this.mimetypeField = value;
            }
        }
        
        /// <remarks/>
        public AttachmentListExternalAttachmentHash hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class AttachmentListExternalAttachmentHash {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd", IsNullable=false)]
    public partial class Signatures {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DepositorServerSignature", typeof(DepositorServerSignature))]
        [System.Xml.Serialization.XmlElementAttribute("DepositorSignature", typeof(SignaturesDepositorSignature))]
        [System.Xml.Serialization.XmlElementAttribute("NonEDP", typeof(SignaturesNonEDP))]
        [System.Xml.Serialization.XmlElementAttribute("PreparerServerSignature", typeof(PreparerServerSignature))]
        [System.Xml.Serialization.XmlElementAttribute("PreparerSignature", typeof(SignaturesPreparerSignature))]
        [System.Xml.Serialization.XmlElementAttribute("ServerSignature", typeof(ServerSignature))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd", IsNullable=false)]
    public partial class DepositorServerSignature {
        
        private serverSignerType depositorField;
        
        private receiptType receiptField;
        
        private System.Xml.XmlElement anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public serverSignerType Depositor {
            get {
                return this.depositorField;
            }
            set {
                this.depositorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public receiptType receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement Any1 {
            get {
                return this.any1Field;
            }
            set {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class SignaturesDepositorSignature {
        
        private signerType depositorField;
        
        private System.Xml.XmlElement anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public signerType Depositor {
            get {
                return this.depositorField;
            }
            set {
                this.depositorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement Any1 {
            get {
                return this.any1Field;
            }
            set {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class SignaturesNonEDP {
        
        private receiptType receiptField;
        
        /// <remarks/>
        public receiptType receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd", IsNullable=false)]
    public partial class PreparerServerSignature {
        
        private serverSignerType preparerField;
        
        private System.Xml.XmlElement anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public serverSignerType Preparer {
            get {
                return this.preparerField;
            }
            set {
                this.preparerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement Any1 {
            get {
                return this.any1Field;
            }
            set {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class SignaturesPreparerSignature {
        
        private signerType preparerField;
        
        private System.Xml.XmlElement anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public signerType Preparer {
            get {
                return this.preparerField;
            }
            set {
                this.preparerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement Any1 {
            get {
                return this.any1Field;
            }
            set {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd", IsNullable=false)]
    public partial class ServerSignature {
        
        private receiptType receiptField;
        
        private System.Xml.XmlElement anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public receiptType receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement Any1 {
            get {
                return this.any1Field;
            }
            set {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    public partial class EnvelopeBody {
        
        private object bodyContentField;
        
        private D_IFI d_IFIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
        public object bodyContent {
            get {
                return this.bodyContentField;
            }
            set {
                this.bodyContentField = value;
            }
        }
        
        /// <remarks/>
        public D_IFI D_IFI {
            get {
                return this.d_IFIField;
            }
            set {
                this.d_IFIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd", IsNullable=false)]
    public partial class D_IFI {
        
        private System.DateTime periodStartField;
        
        private bool periodStartFieldSpecified;
        
        private System.DateTime periodEndField;
        
        private bool periodEndFieldSpecified;
        
        private string telephoneNumberField;
        
        private string emailField;
        
        private TItem[] tItemField;
        
        private D_IFIAttachment[] attachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PeriodStart {
            get {
                return this.periodStartField;
            }
            set {
                this.periodStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PeriodStartSpecified {
            get {
                return this.periodStartFieldSpecified;
            }
            set {
                this.periodStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PeriodEnd {
            get {
                return this.periodEndField;
            }
            set {
                this.periodEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PeriodEndSpecified {
            get {
                return this.periodEndFieldSpecified;
            }
            set {
                this.periodEndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TelephoneNumber {
            get {
                return this.telephoneNumberField;
            }
            set {
                this.telephoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TItem")]
        public TItem[] TItem {
            get {
                return this.tItemField;
            }
            set {
                this.tItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment")]
        public D_IFIAttachment[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd", IsNullable=false)]
    public partial class TItem {
        
        private typeInventory typeIdField;
        
        private string typeField;
        
        private string typeNameField;
        
        private string nameField;
        
        private string codeField;
        
        private string iSINField;
        
        private bool hasForeignTaxField;
        
        private bool hasForeignTaxFieldSpecified;
        
        private decimal foreignTaxField;
        
        private bool foreignTaxFieldSpecified;
        
        private string countryIdField;
        
        private string countryNameField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public typeInventory TypeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string ISIN {
            get {
                return this.iSINField;
            }
            set {
                this.iSINField = value;
            }
        }
        
        /// <remarks/>
        public bool HasForeignTax {
            get {
                return this.hasForeignTaxField;
            }
            set {
                this.hasForeignTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasForeignTaxSpecified {
            get {
                return this.hasForeignTaxFieldSpecified;
            }
            set {
                this.hasForeignTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ForeignTax {
            get {
                return this.foreignTaxField;
            }
            set {
                this.foreignTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForeignTaxSpecified {
            get {
                return this.foreignTaxFieldSpecified;
            }
            set {
                this.foreignTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TShortSubItem", typeof(TShortSubItem))]
        [System.Xml.Serialization.XmlElementAttribute("TSubItem", typeof(TSubItem))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    public enum typeInventory {
        
        /// <remarks/>
        PLIFI,
        
        /// <remarks/>
        PLIFIShort,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd", IsNullable=false)]
    public partial class TShortSubItem {
        
        private object itemField;
        
        private decimal f8Field;
        
        private bool f8FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Purchase", typeof(TShortSubItemPurchase))]
        [System.Xml.Serialization.XmlElementAttribute("Sale", typeof(TShortSubItemSale))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public decimal F8 {
            get {
                return this.f8Field;
            }
            set {
                this.f8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F8Specified {
            get {
                return this.f8FieldSpecified;
            }
            set {
                this.f8FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    public partial class TShortSubItemPurchase {
        
        private System.DateTime f4Field;
        
        private bool f4FieldSpecified;
        
        private typeGainType f5Field;
        
        private bool f5FieldSpecified;
        
        private decimal f6Field;
        
        private bool f6FieldSpecified;
        
        private decimal f7Field;
        
        private bool f7FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime F4 {
            get {
                return this.f4Field;
            }
            set {
                this.f4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F4Specified {
            get {
                return this.f4FieldSpecified;
            }
            set {
                this.f4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public typeGainType F5 {
            get {
                return this.f5Field;
            }
            set {
                this.f5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F5Specified {
            get {
                return this.f5FieldSpecified;
            }
            set {
                this.f5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal F6 {
            get {
                return this.f6Field;
            }
            set {
                this.f6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F6Specified {
            get {
                return this.f6FieldSpecified;
            }
            set {
                this.f6FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal F7 {
            get {
                return this.f7Field;
            }
            set {
                this.f7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F7Specified {
            get {
                return this.f7FieldSpecified;
            }
            set {
                this.f7FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    public enum typeGainType {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        H,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    public partial class TShortSubItemSale {
        
        private System.DateTime f1Field;
        
        private bool f1FieldSpecified;
        
        private decimal f2Field;
        
        private bool f2FieldSpecified;
        
        private decimal f3Field;
        
        private bool f3FieldSpecified;
        
        private bool f9Field;
        
        private bool f9FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime F1 {
            get {
                return this.f1Field;
            }
            set {
                this.f1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F1Specified {
            get {
                return this.f1FieldSpecified;
            }
            set {
                this.f1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal F2 {
            get {
                return this.f2Field;
            }
            set {
                this.f2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F2Specified {
            get {
                return this.f2FieldSpecified;
            }
            set {
                this.f2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal F3 {
            get {
                return this.f3Field;
            }
            set {
                this.f3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F3Specified {
            get {
                return this.f3FieldSpecified;
            }
            set {
                this.f3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool F9 {
            get {
                return this.f9Field;
            }
            set {
                this.f9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F9Specified {
            get {
                return this.f9FieldSpecified;
            }
            set {
                this.f9FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd", IsNullable=false)]
    public partial class TSubItem {
        
        private object itemField;
        
        private decimal f8Field;
        
        private bool f8FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Purchase", typeof(TSubItemPurchase))]
        [System.Xml.Serialization.XmlElementAttribute("Sale", typeof(TSubItemSale))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public decimal F8 {
            get {
                return this.f8Field;
            }
            set {
                this.f8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F8Specified {
            get {
                return this.f8FieldSpecified;
            }
            set {
                this.f8FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    public partial class TSubItemPurchase {
        
        private System.DateTime f1Field;
        
        private bool f1FieldSpecified;
        
        private typeGainType f2Field;
        
        private bool f2FieldSpecified;
        
        private decimal f3Field;
        
        private bool f3FieldSpecified;
        
        private decimal f4Field;
        
        private bool f4FieldSpecified;
        
        private bool f9Field;
        
        private bool f9FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime F1 {
            get {
                return this.f1Field;
            }
            set {
                this.f1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F1Specified {
            get {
                return this.f1FieldSpecified;
            }
            set {
                this.f1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public typeGainType F2 {
            get {
                return this.f2Field;
            }
            set {
                this.f2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F2Specified {
            get {
                return this.f2FieldSpecified;
            }
            set {
                this.f2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal F3 {
            get {
                return this.f3Field;
            }
            set {
                this.f3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F3Specified {
            get {
                return this.f3FieldSpecified;
            }
            set {
                this.f3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal F4 {
            get {
                return this.f4Field;
            }
            set {
                this.f4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F4Specified {
            get {
                return this.f4FieldSpecified;
            }
            set {
                this.f4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool F9 {
            get {
                return this.f9Field;
            }
            set {
                this.f9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F9Specified {
            get {
                return this.f9FieldSpecified;
            }
            set {
                this.f9FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    public partial class TSubItemSale {
        
        private System.DateTime f5Field;
        
        private decimal f6Field;
        
        private decimal f7Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime F5 {
            get {
                return this.f5Field;
            }
            set {
                this.f5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal F6 {
            get {
                return this.f6Field;
            }
            set {
                this.f6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal F7 {
            get {
                return this.f7Field;
            }
            set {
                this.f7Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/D_IFI_4.xsd")]
    public partial class D_IFIAttachment {
        
        private string documentField;
        
        /// <remarks/>
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd", IsNullable=false)]
    public partial class Transformation {
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("localfile", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("url", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        data,
        
        /// <remarks/>
        localfile,
        
        /// <remarks/>
        url,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd", IsNullable=false)]
    public partial class AttachmentList {
        
        private AttachmentListExternalAttachment[] externalAttachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalAttachment")]
        public AttachmentListExternalAttachment[] ExternalAttachment {
            get {
                return this.externalAttachmentField;
            }
            set {
                this.externalAttachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd", IsNullable=false)]
    public partial class NER {
        
        private decimal total_F8Field;
        
        private bool total_F8FieldSpecified;
        
        private decimal total_F9Field;
        
        private bool total_F9FieldSpecified;
        
        private decimal total_F10Field;
        
        private bool total_F10FieldSpecified;
        
        private NERNERItem[] nERItemField;
        
        /// <remarks/>
        public decimal Total_F8 {
            get {
                return this.total_F8Field;
            }
            set {
                this.total_F8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_F8Specified {
            get {
                return this.total_F8FieldSpecified;
            }
            set {
                this.total_F8FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Total_F9 {
            get {
                return this.total_F9Field;
            }
            set {
                this.total_F9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_F9Specified {
            get {
                return this.total_F9FieldSpecified;
            }
            set {
                this.total_F9FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Total_F10 {
            get {
                return this.total_F10Field;
            }
            set {
                this.total_F10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_F10Specified {
            get {
                return this.total_F10FieldSpecified;
            }
            set {
                this.total_F10FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NERItem")]
        public NERNERItem[] NERItem {
            get {
                return this.nERItemField;
            }
            set {
                this.nERItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://edavki.durs.si/Documents/Schemas/EDP-Common-1.xsd")]
    public partial class NERNERItem {
        
        private string f1_NameField;
        
        private string f2_AddressField;
        
        private string f3_ResidentCountryField;
        
        private int f4_TaxNumberField;
        
        private bool f4_TaxNumberFieldSpecified;
        
        private System.DateTime f5_BirthDateField;
        
        private bool f5_BirthDateFieldSpecified;
        
        private string f6_BenefitsField;
        
        private string f7_OtherBenefitsField;
        
        private decimal f8Field;
        
        private bool f8FieldSpecified;
        
        private decimal f9Field;
        
        private bool f9FieldSpecified;
        
        private decimal f10Field;
        
        private bool f10FieldSpecified;
        
        /// <remarks/>
        public string F1_Name {
            get {
                return this.f1_NameField;
            }
            set {
                this.f1_NameField = value;
            }
        }
        
        /// <remarks/>
        public string F2_Address {
            get {
                return this.f2_AddressField;
            }
            set {
                this.f2_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string F3_ResidentCountry {
            get {
                return this.f3_ResidentCountryField;
            }
            set {
                this.f3_ResidentCountryField = value;
            }
        }
        
        /// <remarks/>
        public int F4_TaxNumber {
            get {
                return this.f4_TaxNumberField;
            }
            set {
                this.f4_TaxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F4_TaxNumberSpecified {
            get {
                return this.f4_TaxNumberFieldSpecified;
            }
            set {
                this.f4_TaxNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime F5_BirthDate {
            get {
                return this.f5_BirthDateField;
            }
            set {
                this.f5_BirthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F5_BirthDateSpecified {
            get {
                return this.f5_BirthDateFieldSpecified;
            }
            set {
                this.f5_BirthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string F6_Benefits {
            get {
                return this.f6_BenefitsField;
            }
            set {
                this.f6_BenefitsField = value;
            }
        }
        
        /// <remarks/>
        public string F7_OtherBenefits {
            get {
                return this.f7_OtherBenefitsField;
            }
            set {
                this.f7_OtherBenefitsField = value;
            }
        }
        
        /// <remarks/>
        public decimal F8 {
            get {
                return this.f8Field;
            }
            set {
                this.f8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F8Specified {
            get {
                return this.f8FieldSpecified;
            }
            set {
                this.f8FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal F9 {
            get {
                return this.f9Field;
            }
            set {
                this.f9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F9Specified {
            get {
                return this.f9FieldSpecified;
            }
            set {
                this.f9FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal F10 {
            get {
                return this.f10Field;
            }
            set {
                this.f10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool F10Specified {
            get {
                return this.f10FieldSpecified;
            }
            set {
                this.f10FieldSpecified = value;
            }
        }
    }
}
